/* Starter pack, part 3: three PDFs and three websites per subject (practiced with recall prompts). */
window.LESSONS.push(
  {"id": "st0", "subj": "acting", "topic": "Meisner Repetition", "kind": "pdf", "title": "Meisner Activities List", "url": "https://www.cityheadshots.com/uploads/5/1/2/1/5121840/meisner_activities_list.pdf", },
  {"id": "st1", "subj": "acting", "topic": "Meisner Repetition", "kind": "pdf", "title": "More Than Repetition: Meisner in Actor Training", "url": "https://theatrepractice.us/pdfs/Schebetta%20More%20Than%20Repetition.pdf", },
  {"id": "st2", "subj": "acting", "topic": "Stanislavski’s Magic If", "kind": "pdf", "title": "Stanislavski Knowledge Organiser", "url": "https://www.birchwoodhigh.org/wp-content/uploads/2023/09/Project-1-Drama-Year-9-Stan.pdf", },
  {"id": "st3", "subj": "acting", "topic": "Meisner Repetition", "kind": "link", "title": "Meisner technique (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Meisner_technique", },
  {"id": "st4", "subj": "acting", "topic": "Stanislavski’s Magic If", "kind": "link", "title": "Given circumstances (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Given_circumstances", },
  {"id": "st5", "subj": "acting", "topic": "Uta Hagen", "kind": "link", "title": "Uta Hagen (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Uta_Hagen", },
  {"id": "st6", "subj": "hiset", "topic": "Linear Equations", "kind": "pdf", "title": "HiSET Math Formula Sheet", "url": "https://hiset.org/wp-content/uploads/2025/05/hiset-mathematics-formula-sheet.pdf", },
  {"id": "st7", "subj": "hiset", "topic": "Linear Equations", "kind": "pdf", "title": "HiSET Math Practice Test (half length)", "url": "https://hiset.org/wp-content/uploads/2025/05/hiset_fpt8_mathematics.pdf", },
  {"id": "st8", "subj": "hiset", "topic": "Reading: Main Idea", "kind": "pdf", "title": "HiSET Reading Practice Test (half length)", "url": "https://hiset.org/wp-content/uploads/2025/05/hiset_fpt8_reading.pdf", },
  {"id": "st9", "subj": "hiset", "topic": "Reading: Main Idea", "kind": "link", "title": "Official HiSET practice tests", "url": "https://hiset.org/prepare-for-your-test/practice-tests/", },
  {"id": "st10", "subj": "hiset", "topic": "Reading: Main Idea", "kind": "link", "title": "HiSET test taker resources", "url": "https://hiset.org/resource-library/test-taker/", },
  {"id": "st11", "subj": "hiset", "topic": "Social Studies: Government", "kind": "link", "title": "Separation of powers in the U.S. (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Separation_of_powers_under_the_United_States_Constitution", },
  {"id": "st12", "subj": "anatomy", "topic": "The Heart", "kind": "pdf", "title": "The Anatomy of the Heart (lesson unit)", "url": "https://www.isbe.net/CTEDocuments/HST-L630055.pdf", },
  {"id": "st13", "subj": "anatomy", "topic": "Skeletal System", "kind": "pdf", "title": "Human Skeleton Anatomy Activity (Ask A Biologist)", "url": "https://askabiologist.asu.edu/sites/default/files/resources/coloring_pages/pdf/aab_human_skeleton_anatomy_activity.pdf", },
  {"id": "st14", "subj": "anatomy", "topic": "Respiratory System", "kind": "pdf", "title": "Respiratory System Overview", "url": "https://health.maryland.gov/dda/Pages/Developments/2015/2013%2010-8-13%20Respiratory%20System%20Overview.pdf", },
  {"id": "st15", "subj": "anatomy", "topic": "The Heart", "kind": "link", "title": "How blood flows through the heart (NIH)", "url": "https://www.nhlbi.nih.gov/health/heart/blood-flow", },
  {"id": "st16", "subj": "anatomy", "topic": "Skeletal System", "kind": "link", "title": "Introduction to the Skeletal System (NIH SEER)", "url": "https://training.seer.cancer.gov/anatomy/skeletal/", },
  {"id": "st17", "subj": "anatomy", "topic": "Respiratory System", "kind": "link", "title": "How the lungs work (NIH)", "url": "https://www.nhlbi.nih.gov/health/lungs/respiratory-system", },
  {"id": "st18", "subj": "psych", "topic": "Memory", "kind": "pdf", "title": "Memory: Encoding, Storage, Retrieval (McDermott & Roediger)", "url": "https://peachf.org/images/Science/MemEncodingStorageRetrievalMcDermott.pdf", },
  {"id": "st19", "subj": "psych", "topic": "Memory", "kind": "pdf", "title": "Memory Encoding (lecture notes)", "url": "https://elearn.midlandstech.edu/d2l/lor/viewer/viewFile.d2lfile/13683/248/Memory%20Encoding.pdf", },
  {"id": "st20", "subj": "psych", "topic": "Memory", "kind": "pdf", "title": "Memory (lecture)", "url": "https://drive.uqu.edu.sa/_/masaidahmed/files/psycho/lec006memory.pdf", },
  {"id": "st21", "subj": "psych", "topic": "Memory", "kind": "link", "title": "Memory chapter (NOBA, open textbook)", "url": "https://oertx.highered.texas.gov/courseware/lesson/596/student/", },
  {"id": "st22", "subj": "psych", "topic": "Development", "kind": "link", "title": "Piaget’s theory of cognitive development (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Piaget%27s_theory_of_cognitive_development", },
  {"id": "st23", "subj": "psych", "topic": "Social Thinking", "kind": "link", "title": "Fundamental attribution error (Wikipedia)", "url": "https://en.wikipedia.org/wiki/Fundamental_attribution_error", },
  {"id": "st24", "subj": "spanish", "topic": "Present Tense", "kind": "pdf", "title": "Spanish Regular Verbs: Present Tense (handout)", "url": "https://www.bucks.edu/media/bcccmedialibrary/tutoring/documents/writingareahandoutrevision/spanish/Regular-Present-Tense.pdf", },
  {"id": "st25", "subj": "spanish", "topic": "Present Tense", "kind": "pdf", "title": "Spanish Conjugation Cheat Sheet", "url": "https://www.spanishwithtati.com/wp-content/uploads/2020/10/Spanish-Verbs-Conjugation-Chart.pdf", },
  {"id": "st26", "subj": "spanish", "topic": "Numbers", "kind": "pdf", "title": "Spanish Numbers 0–100 Cheat Sheet", "url": "https://uploads.weconnect.com/mce/8eac9d03673ad3fa86c1c815275470ec81580e0a/School/Spanish/Numeros%200-100%20CHEAT%20SHEET.pdf", },
  {"id": "st27", "subj": "spanish", "topic": "Present Tense", "kind": "link", "title": "Spanish verb conjugation chart (NC State)", "url": "https://faculty.chass.ncsu.edu/despain/lgv/verbos/index.html", },
  {"id": "st28", "subj": "spanish", "topic": "Present Tense", "kind": "link", "title": "Spanish verb conjugation (123TeachMe)", "url": "https://www.123teachme.com/spanish_verb_conjugation", },
  {"id": "st29", "subj": "spanish", "topic": "Numbers", "kind": "link", "title": "Numbers 1–100 worksheets (Woodward Spanish)", "url": "https://www.woodwardspanish.com/resources/numbers-1-100-spanish-worksheets/", },
  {"id": "st30", "subj": "music", "topic": "Reading Notes", "kind": "pdf", "title": "Understanding Basic Music Theory (open textbook)", "url": "https://www.opentextbooks.org.hk/system/files/export/2/2180/pdf/Understanding_Basic_Music_Theory_2180.pdf", },
  {"id": "st31", "subj": "music", "topic": "Rhythm", "kind": "pdf", "title": "Basic Music Theory: How to Read, Write and Understand Music", "url": "https://corcoranhighschoolmusic.weebly.com/uploads/2/9/2/8/29287141/basicmusictheorytextbook.pdf", },
  {"id": "st32", "subj": "music", "topic": "Scales", "kind": "pdf", "title": "Music Theory (open textbook)", "url": "https://2012books.lardbucket.org/pdfs/music-theory.pdf", },
  {"id": "st33", "subj": "music", "topic": "Reading Notes", "kind": "link", "title": "Music theory lessons (musictheory.net)", "url": "https://www.musictheory.net/lessons", },
  {"id": "st34", "subj": "music", "topic": "Rhythm", "kind": "link", "title": "Open Music Theory: Fundamentals", "url": "https://viva.pressbooks.pub/openmusictheory/part/fundamentals/", },
  {"id": "st35", "subj": "music", "topic": "Scales", "kind": "link", "title": "Fundamentals of Music Theory (open textbook)", "url": "https://open.ed.ac.uk/fundamentals-of-music-theory-open-textbook/", }
);
