/* Study Hub content: subjects, topics, lessons (real YouTube videos) and practice questions.
   To add a lesson, add an entry to LESSONS with a YouTube video id and a list of questions.
   Question types: multiple choice (options + answer index) or type:"open" (model answer + what to look for). */

window.SUBJECTS = [
  {id:"acting",  name:"Acting",       topics:["Meisner Repetition","Stanislavski’s Magic If","Uta Hagen"]},
  {id:"hiset",   name:"HiSET",        topics:["Linear Equations","Reading: Main Idea","Social Studies: Government"]},
  {id:"anatomy", name:"Anatomy",      topics:["The Heart","Skeletal System","Respiratory System"]},
  {id:"psych",   name:"Psychology",   topics:["Memory","Development","Social Thinking"]},
  {id:"spanish", name:"Spanish",      topics:["Greetings","Present Tense","Numbers"]},
  {id:"music",   name:"Music Theory", topics:["Reading Notes","Rhythm","Scales"]}
];

window.LESSONS = [
  {
    id:"meisner", subj:"acting", topic:"Meisner Repetition", course:"Acting Fundamentals",
    title:"Understanding Meisner Repetition", videoId:"irHiHN9wXWo", channel:"YouTube",
    questions:[
      {kind:"Concept", prompt:"Meisner described acting as “living truthfully under…”",
       options:["Imaginary circumstances","Stage lighting","The director’s vision","Rehearsed conditions"], answer:0,
       hint:"The situation is invented. Your behaviour inside it isn’t.",
       right:"The circumstances are imaginary, but what you do and feel inside them should be real.",
       wrong:"Think about which part of a scene is made up, and which part should never be."},
      {kind:"Concept", prompt:"In the first stage of repetition, what do partners repeat?",
       options:["Lines from the script","An observation about each other","A tongue twister","Their character’s backstory"], answer:1,
       hint:"It starts with something you can actually see in front of you.",
       right:"Repetition starts from a simple, true observation about your partner, then you pass it back and forth.",
       wrong:"There’s no script yet. Where does the first line come from?"},
      {kind:"Technique identification", prompt:"A says “You’re smiling.” B answers “I’m smiling.” What is B doing?",
       options:["Breaking the exercise","Paraphrasing","Repeating from their own point of view","Adding an activity"], answer:2,
       hint:"Look at the pronoun B changed.",
       right:"B keeps the observation but says it from where they stand. That’s still repetition.",
       wrong:"B didn’t change the meaning. Look closely at which single word changed."},
      {kind:"Concept", prompt:"What is the primary purpose of repetition in the Meisner technique?",
       options:["Memorizing dialogue","Developing truthful reactions","Improving pronunciation","Controlling body movement"], answer:1,
       hint:"Think about what the actor is trying to accomplish rather than what they’re physically doing.",
       right:"Repetition is used to encourage actors to respond truthfully to their scene partner rather than planning their next response.",
       wrong:"The words in repetition are deliberately simple. So the exercise can’t really be about the words."},
      {kind:"What would you do?", type:"open", prompt:"Mid-repetition, your partner suddenly laughs. What do you do?",
       hint:"Is the laugh something you should work around, or something you should use?",
       model:"Let it change you. Notice it (“You’re laughing”) and repeat with whatever it honestly stirs in you, rather than holding on to the old line.",
       look:["You notice the change in your partner","You let it affect how you repeat","You don’t ignore it or push through"]},
      {kind:"Concept", prompt:"What does Meisner mean by a “pinch and an ouch”?",
       options:["A warm-up for the voice","Your partner does something that affects you, and you respond to it","A mistake you should correct","A stage combat cue"], answer:1,
       hint:"The pinch comes from someone else. The ouch comes from you.",
       right:"Something real happens to you (the pinch), and your response is honest (the ouch). No planning in between.",
       wrong:"It isn’t a physical cue. Think of it as cause and effect between two people."},
      {kind:"Concept", prompt:"Where should your attention be during repetition?",
       options:["On your partner","On how you sound","On your next line","On the audience"], answer:0,
       hint:"If you’re thinking about yourself, you can’t notice anything new.",
       right:"All of your attention goes to your partner. That’s what makes truthful reactions possible.",
       wrong:"Three of these options point your attention at yourself. One doesn’t."},
      {kind:"Technique identification", prompt:"Which of these is a strong independent activity?",
       options:["Pacing around the room","Pretending to read a book","Gluing a torn letter back together before your sister gets home","Humming a song"], answer:2,
       hint:"A good activity is hard to do, and you have a reason it matters.",
       right:"It’s physically difficult and has a personal reason and a deadline, so it holds your attention for real.",
       wrong:"Look for the option with real difficulty and a reason behind it."},
      {kind:"Concept", prompt:"Why does Meisner discourage trying to be interesting?",
       options:["It makes scenes run too long","It pulls your attention onto yourself and off your partner","Directors dislike it","It is hard on the voice"], answer:1,
       hint:"Where does your focus go when you try to impress?",
       right:"Trying to be interesting is self-focused. The truth of the scene lives in your partner.",
       wrong:"It’s about focus, not length or preference."},
      {kind:"Recall", prompt:"Complete the principle: “Don’t do anything until…”",
       options:["…the director says so","…you’ve planned your reaction","…something happens to make you do it","…you’ve said your line"], answer:2,
       hint:"This is the pinch and ouch idea, as a rule.",
       right:"Behaviour should be caused by something real happening, not invented ahead of time.",
       wrong:"Planning is exactly what this rule is against."}
    ]
  },
  {
    id:"linear", subj:"hiset", topic:"Linear Equations", course:"HiSET Math",
    title:"How to Solve Linear Equations", videoId:"7DPWeBszNSM", channel:"YouTube",
    questions:[
      {kind:"Math problem", prompt:"Solve for x: 2x + 5 = 17",
       options:["x = 6","x = 11","x = 8.5","x = 12"], answer:0,
       hint:"Undo the + 5 first, then undo the multiplication by 2.",
       right:"Subtract 5 from both sides to get 2x = 12, then divide by 2: x = 6.",
       wrong:"Check your answer by putting it back in: does 2 times it, plus 5, give 17?"},
      {kind:"Concept", prompt:"What is the best first step to solve 3x − 4 = 11?",
       options:["Divide both sides by 3","Add 4 to both sides","Subtract 11 from both sides","Multiply both sides by 4"], answer:1,
       hint:"Work backwards: which operation is ‘furthest’ from the x?",
       right:"Adding 4 to both sides isolates 3x (3x = 15). Then divide by 3 to get x = 5.",
       wrong:"You can divide first, but it creates fractions. Try clearing the constant first."},
      {kind:"Math problem", prompt:"Solve for x: 5(x − 2) = 15",
       options:["x = 1","x = 3","x = 5","x = 17"], answer:2,
       hint:"Either distribute the 5, or divide both sides by 5 first.",
       right:"Divide both sides by 5 to get x − 2 = 3, so x = 5.",
       wrong:"Remember the 5 multiplies both the x and the 2."},
      {kind:"Math problem", prompt:"Solve for x: x ÷ 4 = 3",
       options:["x = 0.75","x = 7","x = 12","x = 1"], answer:2,
       hint:"The opposite of dividing by 4 is…",
       right:"Multiply both sides by 4: x = 12.",
       wrong:"Undo division with multiplication."},
      {kind:"Math problem", prompt:"Solve for x: 4x + 3 = 2x + 11",
       options:["x = 7","x = 4","x = 2","x = 14"], answer:1,
       hint:"Get all the x terms on one side first.",
       right:"Subtract 2x from both sides (2x + 3 = 11), subtract 3 (2x = 8), divide by 2: x = 4.",
       wrong:"Collect the x terms on one side and the numbers on the other."},
      {kind:"Concept", prompt:"Why do you do the same thing to both sides of an equation?",
       options:["It makes the numbers smaller","To keep both sides equal","It’s a HiSET rule","To get rid of negatives"], answer:1,
       hint:"Think of an equation as a balanced scale.",
       right:"An equation is a balance. Whatever you do to one side, you do to the other so it stays balanced.",
       wrong:"Picture a scale. What happens if you only change one side?"}
    ]
  },
  {
    id:"heart", subj:"anatomy", topic:"The Heart", course:"Anatomy & Physiology",
    title:"The Heart, Part 1: Under Pressure", videoId:"X9ZZ6tcxArI", channel:"CrashCourse",
    questions:[
      {kind:"Recall", prompt:"How many chambers does the human heart have?",
       options:["Two","Three","Four","Six"], answer:2,
       hint:"Two upper and two lower.",
       right:"Four: the right and left atria on top, and the right and left ventricles below.",
       wrong:"Think of the upper receiving chambers and the lower pumping chambers on each side."},
      {kind:"Identification", prompt:"Which chamber pumps oxygen-rich blood out to the whole body?",
       options:["Right atrium","Right ventricle","Left atrium","Left ventricle"], answer:3,
       hint:"Ventricles pump out. Oxygen-rich blood is on the left side.",
       right:"The left ventricle pumps oxygenated blood into the aorta and out to the body.",
       wrong:"Which side carries oxygen-rich blood, and which chambers do the pumping?"},
      {kind:"Relationship", prompt:"Blood coming back from the body enters which chamber first?",
       options:["Left atrium","Right atrium","Left ventricle","Right ventricle"], answer:1,
       hint:"Atria receive. This blood has used up its oxygen.",
       right:"Oxygen-poor blood returns through the venae cavae into the right atrium.",
       wrong:"Atria receive blood. Which side handles oxygen-poor blood?"},
      {kind:"Concept", prompt:"The pulmonary arteries carry blood…",
       options:["From the heart to the lungs","From the lungs to the heart","From the heart to the brain","From the body to the heart"], answer:0,
       hint:"Arteries always carry blood away from the heart.",
       right:"Pulmonary arteries take oxygen-poor blood from the right ventricle to the lungs.",
       wrong:"Arteries carry blood away from the heart. Pulmonary means lungs."},
      {kind:"Concept", prompt:"What is the main job of the heart valves?",
       options:["Add oxygen to blood","Keep blood flowing in one direction","Make the heartbeat","Filter the blood"], answer:1,
       hint:"What would happen if blood could slosh backwards?",
       right:"Valves act like one-way doors, so blood can’t flow backwards between beats.",
       wrong:"Valves don’t change the blood itself. Think about direction."},
      {kind:"Recall", type:"open", prompt:"In your own words, trace blood from the body, through the heart and lungs, and back out to the body.",
       hint:"Start at the right atrium.",
       model:"Body → right atrium → right ventricle → pulmonary arteries → lungs (picks up oxygen) → pulmonary veins → left atrium → left ventricle → aorta → body.",
       look:["Right side before the lungs","Lungs in the middle","Left side pumps to the body"]}
    ]
  },
  {
    id:"memory", subj:"psych", topic:"Memory", course:"Psychology",
    title:"How We Make Memories", videoId:"bSycdIx-C48", channel:"CrashCourse",
    questions:[
      {kind:"Concept", prompt:"What are the three basic stages of memory?",
       options:["Seeing, hearing, feeling","Encoding, storage, retrieval","Short, medium, long","Learning, sleeping, waking"], answer:1,
       hint:"Getting it in, keeping it, getting it back out.",
       right:"Encoding gets information in, storage keeps it, and retrieval gets it back out.",
       wrong:"Think of memory like a filing system: putting in, keeping, finding."},
      {kind:"Concept", prompt:"Grouping 5551234567 into 555-123-4567 is an example of…",
       options:["Chunking","Priming","Forgetting","Rehearsal"], answer:0,
       hint:"You made fewer, bigger pieces.",
       right:"Chunking groups items into meaningful units, so short-term memory holds more.",
       wrong:"What changed is how the digits are grouped."},
      {kind:"Scenario", prompt:"You can ride a bike without thinking about how. That’s which kind of memory?",
       options:["Explicit (declarative)","Implicit (procedural)","Sensory","Flashbulb"], answer:1,
       hint:"Could you easily explain every step in words?",
       right:"Skills you do without conscious recall are implicit, procedural memories.",
       wrong:"Explicit memories are facts and events you can consciously state."},
      {kind:"Concept", prompt:"Roughly how many items can short-term memory hold at once?",
       options:["About 2","About 7","About 50","Unlimited"], answer:1,
       hint:"Think of a phone number without the area code.",
       right:"About 7 items, give or take 2, which is why chunking helps so much.",
       wrong:"It’s small, but not that small."},
      {kind:"Application", prompt:"Which study plan leads to better long-term memory?",
       options:["Three hours the night before","Six 30-minute sessions over two weeks","Re-reading notes once","Highlighting the textbook"], answer:1,
       hint:"This is exactly what Remember mode does for you.",
       right:"Spreading practice out over time (the spacing effect) builds stronger memories than cramming.",
       wrong:"Cramming feels productive, but the memories fade fast."},
      {kind:"Application", type:"open", prompt:"Describe how you’d use what you learned to remember a new friend’s name.",
       hint:"Think encoding: meaning, repetition, connection.",
       model:"Say it back right away, connect it to something meaningful (a person or image), use it again in conversation, and recall it later that day.",
       look:["Repeat or rehearse it","Connect it to meaning","Retrieve it again later"]}
    ]
  },
  {
    id:"greetings", subj:"spanish", topic:"Greetings", course:"Spanish",
    title:"Basic Spanish Greetings", videoId:"5TRcUSplhwQ", channel:"YouTube",
    questions:[
      {kind:"Vocabulary", prompt:"What does “Buenos días” mean?",
       options:["Good night","Good morning","Goodbye","Good afternoon"], answer:1,
       hint:"Día means day.",
       right:"“Buenos días” is good morning (literally, good days).",
       wrong:"Día means day. Which greeting is used early in the day?"},
      {kind:"Vocabulary", prompt:"How do you say “good evening / good night”?",
       options:["Buenas tardes","Buenas noches","Buenos días","Hasta mañana"], answer:1,
       hint:"Noche means night.",
       right:"“Buenas noches” works for good evening and good night.",
       wrong:"Tardes is afternoon. Which word means night?"},
      {kind:"Meaning", prompt:"Someone asks “¿Cómo te llamas?” What are they asking?",
       options:["How are you?","Where are you from?","What’s your name?","How old are you?"], answer:2,
       hint:"Llamarse means to be called.",
       right:"“¿Cómo te llamas?” means what’s your name. Answer with “Me llamo…”.",
       wrong:"Think: “How do you call yourself?”"},
      {kind:"Response", prompt:"The best reply to “¿Cómo estás?” is…",
       options:["Me llamo Ana","Bien, gracias","Mucho gusto","De nada"], answer:1,
       hint:"They’re asking how you’re doing.",
       right:"“Bien, gracias” means fine, thanks.",
       wrong:"“¿Cómo estás?” asks how you are."},
      {kind:"Meaning", prompt:"What does “Mucho gusto” mean?",
       options:["Thank you very much","Nice to meet you","I like it a lot","See you soon"], answer:1,
       hint:"You say it when you’re introduced to someone.",
       right:"“Mucho gusto” is nice to meet you.",
       wrong:"It’s said at introductions."},
      {kind:"Situation", prompt:"You meet an older stranger. Which is the polite way to ask how they are?",
       options:["¿Qué tal, amigo?","¿Cómo estás?","¿Cómo está usted?","¿Qué pasa?"], answer:2,
       hint:"Spanish has a formal “you”.",
       right:"“Usted” is the formal you, so “¿Cómo está usted?” is polite with strangers and elders.",
       wrong:"Look for the formal “you”."}
    ]
  },
  {
    id:"notes", subj:"music", topic:"Reading Notes", course:"Music Theory",
    title:"How to Read Notes on the Staff", videoId:"VU8mM1g_g38", channel:"YouTube",
    questions:[
      {kind:"Recall", prompt:"The lines of the treble staff, bottom to top, are…",
       options:["F A C E","E G B D F","G B D F A","A C E G"], answer:1,
       hint:"Every Good Boy Does Fine.",
       right:"E G B D F, remembered as “Every Good Boy Does Fine”.",
       wrong:"FACE is the spaces. Try the famous sentence for the lines."},
      {kind:"Recall", prompt:"The spaces of the treble staff spell…",
       options:["FACE","CAGE","BEAD","EGBDF"], answer:0,
       hint:"It rhymes with space.",
       right:"F A C E, bottom to top. FACE is in the space.",
       wrong:"It’s a four-letter word that rhymes with space."},
      {kind:"Identification", prompt:"A note sits on the middle line of the treble staff. What is it?",
       options:["G","B","D","C"], answer:1,
       hint:"Count the lines: E, G, then…",
       right:"The middle (third) line of the treble staff is B.",
       wrong:"Count up the lines from the bottom: E, G, ?"},
      {kind:"Recall", prompt:"The lines of the bass staff, bottom to top, are…",
       options:["G B D F A","E G B D F","A C E G","F A C E"], answer:0,
       hint:"Good Boys Do Fine Always.",
       right:"G B D F A: “Good Boys Do Fine Always”.",
       wrong:"Bass clef is shifted from treble. Try “Good Boys Do Fine Always”."},
      {kind:"Concept", prompt:"Which letters make up the musical alphabet?",
       options:["A to Z","A to G","C to C","Do to Ti only"], answer:1,
       hint:"It repeats after seven letters.",
       right:"A B C D E F G, then it starts again at A.",
       wrong:"Music uses only seven letter names."},
      {kind:"Identification", prompt:"Where is middle C in the treble clef?",
       options:["On the top line","In the middle space","On one ledger line below the staff","On the bottom line"], answer:2,
       hint:"It sits just outside the staff.",
       right:"Middle C sits on a short ledger line just below the treble staff.",
       wrong:"Middle C is between the treble and bass staves."}
    ]
  }
];
