/* Starter pack, part 2: two more lessons per subject, so no topic is ever empty. */
window.LESSONS.push(
  {
    id:"magicif", subj:"acting", topic:"Stanislavski’s Magic If", course:"Acting Fundamentals",
    title:"Stanislavski’s “Magic If”", videoId:"3a5Qsk3BAzc", channel:"YouTube",
    questions:[
      {kind:"Concept", prompt:"What question does the “Magic If” ask the actor?",
       options:["What would the director want?","What would I do if I were in this situation?","What did the playwright mean?","How would a famous actor play this?"], answer:1,
       hint:"It connects you, personally, to the character’s situation.",
       right:"The Magic If asks “What would I do if I were in these circumstances?”, so your own imagination drives the choice.",
       wrong:"It’s a question about you, not about someone else’s opinion."},
      {kind:"Concept", prompt:"“Given circumstances” are…",
       options:["The props on stage","The facts of the character’s situation: who, where, when, what happened","The actor’s mood that day","The notes from rehearsal"], answer:1,
       hint:"Think of everything the script tells you is true.",
       right:"Given circumstances are the facts of the world: who you are, where and when you are, and what just happened.",
       wrong:"They come from the script’s world, not the rehearsal room."},
      {kind:"Scenario", prompt:"Your character hears a knock late at night. Using the Magic If, you…",
       options:["Look scared because the script says so","Imagine: if I were alone at midnight and heard a knock, what would I actually do?","Copy how an actor did it in a film","Ignore it until your next line"], answer:1,
       hint:"Put yourself inside the circumstances.",
       right:"You let the imagined situation produce a real response, instead of showing an emotion.",
       wrong:"The Magic If starts from the situation, not from the emotion you want to show."},
      {kind:"Concept", prompt:"Why is the Magic If useful?",
       options:["It removes the need to learn lines","It makes believing the character’s situation easier by linking it to your own imagination","It tells you where to stand","It replaces rehearsal"], answer:1,
       hint:"It’s a bridge between you and the character.",
       right:"You don’t have to believe you are the character, only imagine what you’d do if. That’s easier to commit to honestly.",
       wrong:"It’s about belief and imagination, not logistics."},
      {kind:"What would you do?", type:"open", prompt:"Pick a simple scene: you get a letter saying you didn’t get the part. Use the Magic If. What do you do in the first ten seconds?",
       hint:"Where are you? Who else is around? What were you hoping for?",
       model:"Something specific and physical that comes from the situation: you reread the first line, sit down slowly, check if anyone saw, fold the letter away.",
       look:["Your answer is concrete, not “I feel sad”","It comes from the circumstances","It’s something you’d really do"]}
    ]
  },
  {
    id:"hagen", subj:"acting", topic:"Uta Hagen", course:"Acting Fundamentals",
    title:"Uta Hagen’s Basic Object Exercise", videoId:"ll8U_fZbIgo", channel:"YouTube",
    questions:[
      {kind:"Concept", prompt:"What are Uta Hagen’s object exercises mainly about?",
       options:["Memorizing lines faster","Doing simple, real actions truthfully on stage","Projecting your voice","Stage combat"], answer:1,
       hint:"The “objects” are everyday things you use.",
       right:"They train you to perform ordinary actions with real purpose and attention, as you would in life.",
       wrong:"They’re about behaviour with everyday objects, not voice or lines."},
      {kind:"Concept", prompt:"In the exercises, what should every action have?",
       options:["A big emotion","A clear purpose: why you’re doing it right now","Music underneath","An audience reaction"], answer:1,
       hint:"Real people rarely do things for no reason.",
       right:"Each action needs a reason: what you want and why it matters now.",
       wrong:"Think about why people do things in real life."},
      {kind:"Technique identification", prompt:"You’re searching for lost keys before you’re late. Which detail makes it most truthful?",
       options:["Sighing loudly for the audience","Checking the places you’d really check, in the order you’d really check them","Moving fast so it looks urgent","Saying “Where are my keys?” over and over"], answer:1,
       hint:"Hagen cared about real behaviour, not indicating.",
       right:"Specific, logical searching is what a real person does. The urgency comes through the behaviour.",
       wrong:"Avoid showing the audience what you feel. Do what you’d really do."},
      {kind:"Concept", prompt:"Hagen’s “substitution” asks the actor to…",
       options:["Swap roles with a scene partner","Replace the character’s circumstances with a comparable real experience of your own","Use a stand-in during rehearsal","Substitute gestures for dialogue"], answer:1,
       hint:"You borrow from your own life.",
       right:"You find something from your own life that means the same to you, so the character’s situation feels real.",
       wrong:"It’s an inner technique, not a staging trick."},
      {kind:"What would you do?", type:"open", prompt:"Describe how you’d walk into a room to get your phone charger before running to catch a bus.",
       hint:"What do you already know about this room? How much time do you have?",
       model:"You walk straight to where you know it is, unplug it quickly, maybe check the time, and leave, with no extra moves. The time pressure shapes everything.",
       look:["Clear purpose","Specific, efficient actions","The circumstances affect how you move"]}
    ]
  },
  {
    id:"mainidea", subj:"hiset", topic:"Reading: Main Idea", course:"HiSET Reading",
    title:"What Is a Main Idea?", videoId:"4swFGRhQoMI", channel:"Khan Academy",
    questions:[
      {kind:"Concept", prompt:"The main idea of a passage is…",
       options:["The first sentence","The most important point the whole passage is making","The most interesting detail","The title"], answer:1,
       hint:"Which statement do all the other sentences support?",
       right:"It’s the central point that the details all support. It may or may not be the first sentence.",
       wrong:"Details and titles help, but the main idea is the point everything else backs up."},
      {kind:"Reading question", prompt:"“Bees pollinate crops. They make honey. Their wax is used in candles.” The main idea is…",
       options:["Bees make honey","Bees are useful to people in several ways","Candles use wax","Crops need bees"], answer:1,
       hint:"Find what all three sentences have in common.",
       right:"Each sentence is one way bees help us, so the main idea is that bees are useful in several ways.",
       wrong:"That’s one detail. What ties all three together?"},
      {kind:"Concept", prompt:"A supporting detail…",
       options:["Changes the topic","Gives an example, fact or reason that backs up the main idea","Is always a number","Repeats the title"], answer:1,
       hint:"It supports.",
       right:"Supporting details explain or prove the main idea with examples, facts or reasons.",
       wrong:"Details stay on topic and back up the main point."},
      {kind:"Strategy", prompt:"A quick way to check a main idea you’ve picked:",
       options:["See if it’s the longest sentence","Ask whether every paragraph supports it","Pick the sentence with the hardest words","Choose the last sentence"], answer:1,
       hint:"A true main idea covers the whole passage.",
       right:"If every part of the passage supports it, you’ve found the main idea. If only one paragraph does, it’s a detail.",
       wrong:"Length and position don’t decide it. Coverage does."},
      {kind:"Writing practice", type:"open", prompt:"In one sentence, state the main idea of this: “Walking lowers stress. It strengthens your heart. It costs nothing and needs no equipment.”",
       hint:"Combine the three points into one claim.",
       model:"Walking is an easy, free way to improve both your mental and physical health.",
       look:["One sentence","Covers all three details","Doesn’t just repeat one detail"]}
    ]
  },
  {
    id:"branches", subj:"hiset", topic:"Social Studies: Government", course:"HiSET Social Studies",
    title:"Separation of Powers and Checks and Balances", videoId:"0bf3CwYCxXw", channel:"CrashCourse",
    questions:[
      {kind:"Recall", prompt:"What are the three branches of the U.S. government?",
       options:["Federal, state, local","Legislative, executive, judicial","House, Senate, President","Army, Navy, Air Force"], answer:1,
       hint:"Make laws, carry out laws, interpret laws.",
       right:"Legislative (Congress) makes laws, executive (President) carries them out, judicial (courts) interprets them.",
       wrong:"Think about the three jobs: making, enforcing, interpreting laws."},
      {kind:"Concept", prompt:"Which branch makes the laws?",
       options:["Executive","Judicial","Legislative","The military"], answer:2,
       hint:"Congress.",
       right:"The legislative branch, Congress (the House and Senate), writes and passes laws.",
       wrong:"The President carries out laws. Who writes them?"},
      {kind:"Concept", prompt:"The President vetoing a bill is an example of…",
       options:["Federalism","A check on the legislative branch","Judicial review","An amendment"], answer:1,
       hint:"One branch limiting another.",
       right:"A veto lets the executive check Congress. Congress can override it with a two-thirds vote.",
       wrong:"It’s one branch limiting another’s power."},
      {kind:"Concept", prompt:"Why did the framers separate powers?",
       options:["To make laws pass faster","To keep any one branch from becoming too powerful","To save money","To give states more votes"], answer:1,
       hint:"They were worried about tyranny.",
       right:"Splitting power and letting branches check each other prevents any one group from taking total control.",
       wrong:"It’s about limiting power, not speed or cost."},
      {kind:"Application", prompt:"The Supreme Court strikes down a law as unconstitutional. This is called…",
       options:["A veto","Impeachment","Judicial review","A filibuster"], answer:2,
       hint:"The courts reviewing laws.",
       right:"Judicial review is the courts’ power to rule that a law violates the Constitution.",
       wrong:"Vetoes and filibusters belong to other branches."}
    ]
  },
  {
    id:"skeleton", subj:"anatomy", topic:"Skeletal System", course:"Anatomy & Physiology",
    title:"The Skeletal System", videoId:"rDGqkMHPDqE", channel:"CrashCourse",
    questions:[
      {kind:"Recall", prompt:"About how many bones are in the adult human body?",
       options:["106","206","306","406"], answer:1,
       hint:"Babies have more; many fuse as we grow.",
       right:"Adults have 206 bones. Babies start with more, and some fuse together.",
       wrong:"It’s a little over two hundred."},
      {kind:"Concept", prompt:"Which of these is NOT a job of the skeleton?",
       options:["Support and protection","Making blood cells","Storing minerals like calcium","Digesting food"], answer:3,
       hint:"Three of these happen in or with bone.",
       right:"Bones support, protect, store minerals and make blood cells in marrow. Digestion is another system’s job.",
       wrong:"Bone marrow makes blood cells, and bones store calcium. Which one doesn’t fit?"},
      {kind:"Identification", prompt:"Where are new blood cells made?",
       options:["In the red bone marrow","In the cartilage","In the ligaments","In compact bone"], answer:0,
       hint:"It’s inside certain bones.",
       right:"Red bone marrow makes red blood cells, white blood cells and platelets.",
       wrong:"Look inside the bone, in the soft tissue."},
      {kind:"Relationship", prompt:"Osteoblasts and osteoclasts…",
       options:["Both carry oxygen","Build new bone and break down old bone","Connect muscle to bone","Are types of joints"], answer:1,
       hint:"Blast builds; clast cuts.",
       right:"Osteoblasts build bone and osteoclasts break it down, so bone is constantly being remodeled.",
       wrong:"Remember: “blast” builds, “clast” breaks down."},
      {kind:"Concept", prompt:"Bone is described as living tissue because…",
       options:["It never changes","It has cells, blood supply and constantly remodels","It’s made only of calcium","It’s soft"], answer:1,
       hint:"Think about what happens when you break one.",
       right:"Bone has living cells and blood vessels, heals and remodels throughout life.",
       wrong:"If bone were dead, it couldn’t heal a fracture."}
    ]
  },
  {
    id:"lungs", subj:"anatomy", topic:"Respiratory System", course:"Anatomy & Physiology",
    title:"Respiratory System, Part 1", videoId:"bHZsvBdUC2I", channel:"CrashCourse",
    questions:[
      {kind:"Identification", prompt:"Where does gas exchange happen in the lungs?",
       options:["Trachea","Bronchi","Alveoli","Larynx"], answer:2,
       hint:"Tiny air sacs at the very end of the airways.",
       right:"In the alveoli, oxygen moves into the blood and carbon dioxide moves out.",
       wrong:"The trachea and bronchi only carry air. Where does it meet the blood?"},
      {kind:"Relationship", prompt:"In the alveoli, which way do the gases move?",
       options:["Oxygen out of blood, CO₂ into blood","Oxygen into blood, CO₂ out of blood","Both into blood","Both out of blood"], answer:1,
       hint:"You breathe in oxygen and breathe out carbon dioxide.",
       right:"Oxygen diffuses into the blood, and carbon dioxide diffuses out to be exhaled.",
       wrong:"What do you breathe in, and what do you breathe out?"},
      {kind:"Concept", prompt:"Which muscle does most of the work when you breathe in?",
       options:["The heart","The diaphragm","The biceps","The tongue"], answer:1,
       hint:"A dome-shaped muscle under the lungs.",
       right:"The diaphragm contracts and flattens, enlarging the chest so air rushes in.",
       wrong:"It sits right under the lungs."},
      {kind:"Identification", prompt:"The windpipe is also called the…",
       options:["Esophagus","Trachea","Pharynx","Bronchiole"], answer:1,
       hint:"Not the food pipe.",
       right:"The trachea carries air from the larynx down to the bronchi.",
       wrong:"The esophagus carries food. Which carries air?"},
      {kind:"Recall", type:"open", prompt:"Trace a breath of air from your nose to your blood.",
       hint:"Nose, then down the tubes, getting smaller.",
       model:"Nose/mouth → pharynx → larynx → trachea → bronchi → bronchioles → alveoli → oxygen crosses into the capillaries.",
       look:["Order is right","Ends at the alveoli","Mentions crossing into the blood"]}
    ]
  },
  {
    id:"piaget", subj:"psych", topic:"Development", course:"Psychology",
    title:"The Growth of Knowledge (Piaget)", videoId:"8nz2dtv--ok", channel:"CrashCourse",
    questions:[
      {kind:"Recall", prompt:"Piaget’s four stages, in order, are…",
       options:["Sensorimotor, preoperational, concrete operational, formal operational","Oral, anal, phallic, genital","Trust, autonomy, initiative, industry","Infant, toddler, child, teen"], answer:0,
       hint:"Senses first, abstract thinking last.",
       right:"Sensorimotor, preoperational, concrete operational, formal operational.",
       wrong:"Two of these lists belong to Freud and Erikson."},
      {kind:"Concept", prompt:"Object permanence means…",
       options:["Objects never break","Knowing things still exist when you can’t see them","Remembering object names","Preferring familiar toys"], answer:1,
       hint:"Why peekaboo stops being surprising.",
       right:"It’s understanding that objects keep existing when they’re out of sight, developed in the sensorimotor stage.",
       wrong:"Think about a baby looking for a hidden toy."},
      {kind:"Scenario", prompt:"A child says a tall thin glass holds more juice than a short wide one with the same amount. They haven’t mastered…",
       options:["Object permanence","Conservation","Abstract reasoning","Language"], answer:1,
       hint:"The amount stayed the same; only the shape changed.",
       right:"Conservation is knowing quantity stays the same when shape changes. It comes in the concrete operational stage.",
       wrong:"The child can see the juice. The issue is whether the amount changed."},
      {kind:"Concept", prompt:"Schemas are…",
       options:["Mental frameworks for organizing information","Types of memory loss","Parenting styles","Brain regions"], answer:0,
       hint:"Piaget’s building blocks of thinking.",
       right:"Schemas are mental frameworks. We assimilate new info into them or accommodate by changing them.",
       wrong:"They’re concepts or frameworks in the mind."},
      {kind:"Application", prompt:"A toddler calls every four-legged animal “doggy.” This is…",
       options:["Accommodation","Assimilation","Conservation","Egocentrism"], answer:1,
       hint:"Fitting new things into an existing schema.",
       right:"Assimilation: the child fits new animals into the existing “doggy” schema. Learning “cow” would be accommodation.",
       wrong:"The child isn’t changing their schema yet, just using the one they have."}
    ]
  },
  {
    id:"socialthink", subj:"psych", topic:"Social Thinking", course:"Psychology",
    title:"Social Thinking", videoId:"h6HLDV0T5Q8", channel:"CrashCourse",
    questions:[
      {kind:"Concept", prompt:"The fundamental attribution error is…",
       options:["Blaming the situation for everything","Overestimating personality and underestimating the situation when judging others","Forgetting people’s names","Agreeing with the group"], answer:1,
       hint:"How we explain other people’s behaviour.",
       right:"We tend to explain others’ actions by their character, while overlooking the situation they’re in.",
       wrong:"It’s about the mistake we make judging others."},
      {kind:"Scenario", prompt:"Someone cuts you off in traffic and you think “What a jerk.” Later you cut someone off because you’re late. This shows…",
       options:["Conformity","The fundamental attribution error","Cognitive dissonance","Groupthink"], answer:1,
       hint:"You excuse yourself with the situation, but not them.",
       right:"You blamed their character but your own situation, which is the fundamental attribution error.",
       wrong:"Compare how you explained their behaviour versus yours."},
      {kind:"Concept", prompt:"Cognitive dissonance is…",
       options:["Discomfort when our actions and beliefs don’t match","A memory disorder","Hearing two sounds at once","Disagreeing in a group"], answer:0,
       hint:"Dissonance means clash.",
       right:"It’s the tension we feel when actions and beliefs conflict, which pushes us to change one of them.",
       wrong:"It’s an inner clash, not a disagreement with others."},
      {kind:"Concept", prompt:"The foot-in-the-door phenomenon means…",
       options:["People agree to a big request more after agreeing to a small one","People slam doors when angry","First impressions are permanent","People avoid salespeople"], answer:0,
       hint:"Start small.",
       right:"Agreeing to a small request makes people more likely to agree to a bigger one later.",
       wrong:"It’s a persuasion pattern."},
      {kind:"Application", type:"open", prompt:"Think of a time you judged someone quickly. What situation might have explained their behaviour?",
       hint:"What might their day have been like?",
       model:"A good answer names a real moment and a believable situational reason (tired, stressed, bad news) instead of a character flaw.",
       look:["A specific moment","A situational explanation","Not just a label like “rude”"]}
    ]
  },
  {
    id:"presente", subj:"spanish", topic:"Present Tense", course:"Spanish",
    title:"Present Tense: Regular -AR, -ER, -IR Verbs", videoId:"8HWXJjxvOTE", channel:"YouTube",
    questions:[
      {kind:"Conjugation", prompt:"Hablar, yo form:",
       options:["hablo","hablas","habla","hablamos"], answer:0,
       hint:"Yo forms usually end in -o.",
       right:"Yo hablo: I speak. Drop -ar, add -o.",
       wrong:"Drop -ar and add the yo ending."},
      {kind:"Conjugation", prompt:"Comer, tú form:",
       options:["como","comes","comas","comen"], answer:1,
       hint:"-ER verbs: tú ends in -es.",
       right:"Tú comes: you eat.",
       wrong:"For -er verbs, tú takes -es."},
      {kind:"Conjugation", prompt:"Vivir, nosotros form:",
       options:["vivemos","vivimos","viven","vivamos"], answer:1,
       hint:"-IR verbs keep the i in nosotros.",
       right:"Nosotros vivimos: we live. -IR verbs use -imos.",
       wrong:"-ER uses -emos, -IR uses…"},
      {kind:"Meaning", prompt:"“Ellos estudian” means…",
       options:["I study","They study","We study","You study"], answer:1,
       hint:"Ellos = they.",
       right:"Ellos estudian: they study.",
       wrong:"Look at the subject pronoun."},
      {kind:"Concept", prompt:"To conjugate a regular verb in the present tense, you…",
       options:["Add endings to the full infinitive","Drop -ar/-er/-ir and add the ending for the subject","Change the first letter","Use the infinitive as is"], answer:1,
       hint:"Stem + ending.",
       right:"Remove the infinitive ending to get the stem, then add the ending that matches who’s doing it.",
       wrong:"Think stem plus ending."}
    ]
  },
  {
    id:"numeros", subj:"spanish", topic:"Numbers", course:"Spanish",
    title:"Spanish Numbers 1–20", videoId:"4H8bvDe1oaY", channel:"YouTube",
    questions:[
      {kind:"Vocabulary", prompt:"How do you say 7 in Spanish?",
       options:["seis","siete","ocho","sesenta"], answer:1,
       hint:"It starts like “sie…”.",
       right:"Siete is seven.",
       wrong:"Seis is 6 and ocho is 8."},
      {kind:"Vocabulary", prompt:"“Quince” is…",
       options:["5","14","15","50"], answer:2,
       hint:"Think of a quinceañera.",
       right:"Quince is fifteen, as in quinceañera (a 15th birthday).",
       wrong:"Cinco is 5 and catorce is 14."},
      {kind:"Vocabulary", prompt:"How do you say 12?",
       options:["doce","dos","diez","trece"], answer:0,
       hint:"Sounds a bit like dozen.",
       right:"Doce is twelve (a dozen).",
       wrong:"Dos is 2, diez is 10, trece is 13."},
      {kind:"Pattern", prompt:"16 to 19 are written as one word starting with…",
       options:["veinti-","dieci-","quin-","tre-"], answer:1,
       hint:"“Ten and six.”",
       right:"Dieciséis, diecisiete, dieciocho, diecinueve: ten-and-six, ten-and-seven…",
       wrong:"Veinti- is for the twenties."},
      {kind:"Vocabulary", prompt:"“Veinte” means…",
       options:["2","12","20","200"], answer:2,
       hint:"The next word after diecinueve.",
       right:"Veinte is twenty.",
       wrong:"It comes right after diecinueve (19)."}
    ]
  },
  {
    id:"rhythm", subj:"music", topic:"Rhythm", course:"Music Theory",
    title:"Understanding Basic Rhythm", videoId:"ZoxN0wOmw-Q", channel:"YouTube",
    questions:[
      {kind:"Recall", prompt:"In 4/4 time, how many beats does a whole note last?",
       options:["1","2","3","4"], answer:3,
       hint:"It fills the whole measure.",
       right:"A whole note lasts 4 beats, a full measure of 4/4.",
       wrong:"Whole means the whole measure."},
      {kind:"Recall", prompt:"A half note lasts…",
       options:["1 beat","2 beats","4 beats","Half a beat"], answer:1,
       hint:"Half of a whole note.",
       right:"A half note is 2 beats, half of a whole note.",
       wrong:"Half of four is…"},
      {kind:"Recall", prompt:"A quarter note lasts…",
       options:["1 beat","2 beats","4 beats","A quarter of a beat"], answer:0,
       hint:"A quarter of a whole note.",
       right:"A quarter note gets 1 beat in 4/4.",
       wrong:"Four of them fill a 4/4 measure."},
      {kind:"Concept", prompt:"In the time signature 4/4, the top number tells you…",
       options:["How fast to play","How many beats are in each measure","How loud to play","Which note is first"], answer:1,
       hint:"Top = how many.",
       right:"The top number is beats per measure. The bottom 4 means the quarter note gets the beat.",
       wrong:"Time signatures are about counting, not speed or volume."},
      {kind:"Math problem", prompt:"Which fills exactly one measure of 4/4?",
       options:["Two whole notes","One half note + two quarter notes","Three half notes","One quarter note"], answer:1,
       hint:"Add the beats: whole 4, half 2, quarter 1.",
       right:"2 + 1 + 1 = 4 beats, exactly one measure.",
       wrong:"Add up the beats and look for exactly 4."}
    ]
  },
  {
    id:"majorscale", subj:"music", topic:"Scales", course:"Music Theory",
    title:"Whole Steps, Half Steps and the Major Scale", videoId:"Er_54wStpBs", channel:"YouTube",
    questions:[
      {kind:"Concept", prompt:"A half step is…",
       options:["The distance to the very next key, black or white","Two keys apart","An octave","Half a scale"], answer:0,
       hint:"The smallest distance on a piano.",
       right:"A half step moves to the very next key, with nothing in between.",
       wrong:"It’s the smallest possible move."},
      {kind:"Concept", prompt:"A whole step equals…",
       options:["One half step","Two half steps","Three half steps","An octave"], answer:1,
       hint:"Whole = two halves.",
       right:"A whole step is two half steps, skipping one key.",
       wrong:"Two halves make a whole."},
      {kind:"Recall", prompt:"The major scale pattern is…",
       options:["W W H W W W H","W H W W H W W","H W W H W W W","W W W H W W H"], answer:0,
       hint:"Whole, whole, half…",
       right:"Whole, whole, half, whole, whole, whole, half.",
       wrong:"It starts with two whole steps, then a half."},
      {kind:"Identification", prompt:"Which major scale uses only white keys?",
       options:["G major","C major","D major","F major"], answer:1,
       hint:"The first scale most people learn.",
       right:"C major: C D E F G A B C, no sharps or flats.",
       wrong:"G has F♯, D has two sharps, F has B♭."},
      {kind:"Identification", prompt:"Between which two white keys is there a natural half step (no black key)?",
       options:["C and D","E and F","F and G","A and B"], answer:1,
       hint:"Look for white keys touching with no black key between.",
       right:"E–F (and B–C) are natural half steps.",
       wrong:"Find the white keys with no black key between them."}
    ]
  }
);
